apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepsearchapp
spec:
  selector:
    matchLabels:
      app: deepsearchapp
  template:
    metadata:
      labels:
        app: deepsearchapp
    spec:
      containers:
      - name: deepsearchapp
        image: kishores\deepsearchapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
